"""Domain layer packages."""

from .models import (
    ProblemType,
    ExamState,
    IngestionPreviewStatus,
    GradingStatus,
    SolutionGenerationStatus,
    CoachingRole,
    CorrectAnswer,
    SourceImage,
    Extraction,
    EditableDraft,
    Origin,
    Tracking,
    ClientMeta,
    SelectionPolicyConfig,
    ExamConfigSnapshot,
    ProblemSnapshot,
    ExamItemAnswer,
    ExamItemGrading,
    ExamItem,
    ExamSummary,
    User,
    Session,
    IngestionPreview,
    Problem,
    Exam,
    SolutionGenerationTask,
    CanonicalSolution,
    CoachingMessage,
    CoachingConversation,
)
from .normalization import normalize_answer
from .selection import select_problems
from .state import (
    recover_stale_preview,
    transition_preview_state,
    transition_exam_state,
    InvalidStateTransitionError,
)
from .scoring import compute_summary

__all__ = [
    "ProblemType",
    "ExamState",
    "IngestionPreviewStatus",
    "GradingStatus",
    "SolutionGenerationStatus",
    "CoachingRole",
    "CorrectAnswer",
    "SourceImage",
    "Extraction",
    "EditableDraft",
    "Origin",
    "Tracking",
    "ClientMeta",
    "SelectionPolicyConfig",
    "ExamConfigSnapshot",
    "ProblemSnapshot",
    "ExamItemAnswer",
    "ExamItemGrading",
    "ExamItem",
    "ExamSummary",
    "User",
    "Session",
    "IngestionPreview",
    "Problem",
    "Exam",
    "SolutionGenerationTask",
    "CanonicalSolution",
    "CoachingMessage",
    "CoachingConversation",
    "normalize_answer",
    "recover_stale_preview",
    "select_problems",
    "transition_preview_state",
    "transition_exam_state",
    "InvalidStateTransitionError",
    "compute_summary",
]
